[project]
name = "ti84-graphing-calculator"
version = "0.1.0"
description = "A Python implementation of a TI-84 graphing calculator with GUI interface"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
]
